config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root 'dashboard#index'

  devise_scope :user do
    get "/sign_up" => "devise/registrations#new", as: :new_user_registration
    get '/sign_in', to: 'devise/sessions#new', as: :new_user_session
    post '/sign_in', to: 'devise/sessions#create', as: :user_session
    delete '/sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users, controllers: {:registrations => :registrations}, skip: [:sessions]
  resources :users, :only => ['index', 'show']

  resources :payments
  resources :materials
  resources :expences
  resources :articles
  
  
  get 'reports', to: 'reports#index'
  get 'report_by_date', to: 'reports#report_by_date'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/expence.rb
class Expence < ApplicationRecord
  include Reportable

  belongs_to :user

  validates :expence, :expence_value, presence: true
  validates :expence, length: {maximum: 100}
  validates :expence_value, numericality: { :greater_than_or_equal_to => 0 }

  #
  # Подсчет общей суммы расходов то датам
  #
  def self.total_expence_report(period)
    #total_expence = 0
    #period.each do |expence|
    #  total_expence += expence.expence_value
    #end
    return period.collect(&:expence_value).sum
  end
end

app/controllers/expences_controller.rb
class ExpencesController < ApplicationController
  before_action :set_expence, only: [:show, :edit, :update, :destroy]

  # GET /expences
  # GET /expences.json
  def index
    @expences = Expence.all
    @expence = Expence.new
  end

  # GET /expences/1
  # GET /expences/1.json
  def show
  end

  # GET /expences/new
  def new
    @expence = Expence.new
  end

  # GET /expences/1/edit
  def edit
  end

  # POST /expences
  # POST /expences.json
  def create
    @expence = current_user.expences.new(expence_params)

    respond_to do |format|
      if @expence.save
        format.html { redirect_to expences_path, notice: 'Расход успешно добавлен.' }
        format.json { render :show, status: :created, location: @expence }
      else
        format.html { render :new }
        format.json { render json: @expence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expences/1
  # PATCH/PUT /expences/1.json
  def update
    respond_to do |format|
      if @expence.update(expence_params)
        format.html { redirect_to @expence, notice: 'Расход успешно изменен.' }
        format.json { render :show, status: :ok, location: @expence }
      else
        format.html { render :edit }
        format.json { render json: @expence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expences/1
  # DELETE /expences/1.json
  def destroy
    @expence.destroy
    respond_to do |format|
      format.html { redirect_to expences_url, notice: 'Расход успешно удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expence
      @expence = Expence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expence_params
      params.require(:expence).permit(:user_id, :expence, :expence_description, :expence_value)
    end
end

app/helpers/expences_helper.rb
module ExpencesHelper
end

app/views/expences/_expence.html.haml
%table.table.table-sm.table-hover
  %thead
    %tr
      %th.text-center Расход
      %th.text-center Сумма
      %th.text-center Описание 
      %th

  %tbody
    - @expences.report_today.each do |expence|
      %tr
        %td.text-center
          = expence.expence
        %td.text-center
          = expence.expence_value
        %td
          = expence.expence_description
        %td.text-center
          = link_to expence, class: 'show_material' do
            %span.fa.fa-info{"aria-hidden" => "true", 'data-toggle' => 'tooltip', placement: 'left', title: 'Детальная инфомация'} &nbsp
          = link_to expence, :method => :delete,
                              :data => { :confirm => 'Точно?.. Уверен?..' } do
            %span.fa.fa-close{"aria-hidden" => "true", 'data-toggle' => 'tooltip', placement: 'left', title: 'Удалить'}

app/views/expences/_form.html.haml
= simple_form_for(@expence, wrapper: :inline_form) do |f|
  = f.error_notification
  .form-inline
    #modalExpence.modal.fade{:role => "dialog", :tabindex => "-1"}
      .modal-dialog.modal-sm
        .modal-content
          .modal-header
            %h4.modal-title Расход:
            %button.close{"data-dismiss" => "modal", :type => "button"}
              .fa.fa-close
          .modal-body.container-fluid
            .row
              .col
                .form-group
                  %label
                    Расход:
                  .input-group
                    = f.input :expence,
                              label: 'Расход:',
                              placeholder: 'Расход',
                              autofocus: true
            .row
              .col
                .form-group
                  %label
                    Сумма расхода:
                  .input-group
                    = f.input :expence_value,
                              label: 'Сумма расхода:',
                              placeholder: 'Сумма расхода',
                              autofocus: true
            .row
              .col
                .form-group
                  %label
                    Описание расхода:
                  .input-group
                    = f.input :expence_description,
                              label: 'Описание расхода:',
                              placeholder: 'Описание расхода',
                              as: :text
          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Отмена
            = f.button :submit, 'Подтвердить',
                       class: 'btn',
                       id: 'submit'

app/views/expences/edit.html.haml
%h1 Editing expence

= render 'form'

= link_to 'Show', @expence
\|
= link_to 'Back', expences_path

app/views/expences/index.html.haml
= provide(:title, 'Расходы')

.container
  %button.btn.btn-sm{"data-target" => "#modalExpence", "data-toggle" => "modal", :type => "button"}
    Новый расход

#expence
  = render ('expences/form')
%br
#title_expence
  %h4 Список расходов за #{(Date.today).strftime('%d.%m.%Y')}:
#expences
  = render @expence

app/views/expences/new.html.haml
%h1 New expence

= render 'form'

= link_to 'Back', expences_path

app/views/expences/show.html.haml
%p#notice= notice

%p
  %b User:
  = @expence.user
%p
  %b Expence:
  = @expence.expence
%p
  %b Expence description:
  = @expence.expence_description
%p
  %b Expence cence value:
  = @expence.expence_value

= link_to 'Edit', edit_expence_path(@expence)
\|
= link_to 'Back', expences_path