config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root 'dashboard#index'

  devise_scope :user do
    get "/sign_up" => "devise/registrations#new", as: :new_user_registration
    get '/sign_in', to: 'devise/sessions#new', as: :new_user_session
    post '/sign_in', to: 'devise/sessions#create', as: :user_session
    delete '/sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users, controllers: {:registrations => :registrations}, skip: [:sessions]
  resources :users, :only => ['index', 'show']

  resources :payments
  resources :materials
  resources :expences
  resources :articles
  
  
  get 'reports', to: 'reports#index'
  get 'report_by_date', to: 'reports#report_by_date'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/concerns/report.rb
module Report
  extend ActiveSupport::Concern

  module ClassMethods
    #
    # Выборки по датам
    #
    def report_today
      where("updated_at >= ?", Date.today.to_date)
    end

    def report_week
      now = Date.today.to_date
      if now.wednesday?
        now -= 6.day
        where('updated_at >= ? AND updated_at <= ?', now, Date.today.to_date + 1.day)
      else
        until now.wednesday?
          now -= 1.day
        end
        where('updated_at >= ? AND updated_at <= ?', now, Date.today.to_date + 1.day)
      end
    end

    def report_month
      year = Date.today.year
      month = Date.today.month
      where('updated_at >= ? AND updated_at <= ?', Date.new(year, month, 1), Date.today.to_date + 1.day)
    end

    def report_by_date(start_date, end_date)
      where('updated_at >= ? AND updated_at <= ?', start_date, end_date)
    end

    #
    # Подсчет общей суммы расходов то датам
    #
    def total_and_percent_report(period)
      total_report_today,  percent_report_today = 0, 0
      period.each do |report|
        total_report_today += report.payment_total
      end
      percent_report_today = total_report_today * 0.05
      return total_report_today,  percent_report_today, period.length
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @payments_today = Payment.report_today
    @payments_week = Payment.report_week
    @payments_month = Payment.report_month
    @expences_today = Expence.report_today
    @expences_week = Expence.report_week
    @expences_month = Expence.report_month
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "Report_from_#{(Date.today - 6.day).strftime('%d.%m.%Y')}_to_#{(Date.today).strftime('%d.%m.%Y')}",
               template: 'reports/pdf_report.html.haml',
               page_size: "A4",
               disposition: 'attachment'
      end
    end
  end

  def report_by_date
    @payments_by_date = Payment.report_by_date(params[:start_date], params[:end_date])
    @expences_by_date = Expence.report_by_date(params[:start_date], params[:end_date])
    respond_to do |format|
      format.js
    end
  end
  private
    def report_params
      params.require(:report).permit(:start_date, :end_date)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_report.html.haml
%blockquote.blockquote
  .text-justify
    %span{style: "padding: 0px 10px;"} &nbsp
    Сумма в кассе (за вычетом процента оператора и дополнительных расходов) - 
    %strong
      #{payments.total_and_percent_report(payments)[1] - payments.total_and_percent_report(payments)[2] - expences.total_expence_report(expences)}
    грн.
    %footer.blockquote-footer.blockquote-reverse
      Клиентов за период -
      %strong
        #{payments.total_and_percent_report(payments)[0]}
    %footer.blockquote-footer.blockquote-reverse
      Всего платежей на сумму -
      %strong
        #{payments.total_and_percent_report(payments)[1]} 
      грн.
    %footer.blockquote-footer.blockquote-reverse
      Всего новых подключений -
      %strong
        #{payments.total_new_connection_report(payments)[0]} 
    %footer.blockquote-footer.blockquote-reverse
      Всего новых подключений на сумму -
      %strong
        #{payments.total_new_connection_report(payments)[1]} 
      грн.
    %footer.blockquote-footer.blockquote-reverse
      Процент оператора
      %strong
        #{payments.total_and_percent_report(payments)[2]} 
      грн.
    %footer.blockquote-footer.blockquote-reverse
      Дополнительные раходы -
      %strong
        #{expences.total_expence_report(expences)}
      грн.

%h4 Расходы (детально)
%table.table.table-sm.table-hover
  %thead
    %tr
      %th.text-center Расход
      %th.text-center Сумма
      %th.text-center Описание 
      %th
  %tbody
    - expences.each do |expence|
      %tr
        %td.text-center
          = expence.expence
        %td.text-center
          = expence.expence_value
        %td
          = expence.expence_description
        %td.text-center
          = link_to expence, class: 'show_material' do
            %span.fa.fa-info{"aria-hidden" => "true", 'data-toggle' => 'tooltip', placement: 'left', title: 'Детальная инфомация'} &nbsp
          = link_to expence, :method => :delete,
                              :data => { :confirm => 'Точно?.. Уверен?..' } do
            %span.fa.fa-close{"aria-hidden" => "true", 'data-toggle' => 'tooltip', placement: 'left', title: 'Удалить'}

%br
%h4 Платежи (детально)
%table.table.table-sm.table-hover
  %thead
    %tr
      %th.text-center Адрес клиента
      %th.text-center ФИО клиента
      %th.text-center Новый?
      %th.text-center Пополнение
      %th.text-center Материалы
      %th.text-center Всего

  %tbody
    - payments.each do |payment|
      %tr
        %td.text-left= payment.client_address
        %td.text-left= payment.client_name
        %td.text-center
          - if payment.client_new_connection?
            %span.fa.fa-check
        %td.text-center= payment.client_payment
        %td.text-center= payment.used_material
        %td.text-center= payment.payment_total
        %td
          = link_to payment do
            %span.fa.fa-info{'aria-hidden' => 'true', 'data-toggle' => 'tooltip', placement: 'left', title: 'Детальная инфомация'} &nbsp
          = link_to payment, :method => :delete,
                             :data => { :confirm => 'Точно?.. Уверен?..' } do
            %span.fa.fa-close{'aria-hidden' => 'true', 'data-toggle' => 'tooltip', placement: 'left', title: 'Удалить'}

app/views/reports/_report_detail.html.haml
%h4 Расходы (детально)
%table.table.table-sm.table-hover
  %thead
    %tr
      %th.text-center Дата
      %th.text-center Расход
      %th.text-center Сумма
      %th.text-center Описание 
      %th
  %tbody
    - expences.each do |expence|
      %tr
        %td.text-center
          = expence.created_at.strftime('%d.%m.%Y')
        %td.text-center
          = expence.expence
        %td.text-center
          = expence.expence_value
        %td
          = expence.expence_description
        %td.text-center
          = link_to expence, class: 'show_material' do
            %span.fa.fa-info{"aria-hidden" => "true", 'data-toggle' => 'tooltip', placement: 'left', title: 'Детальная инфомация'} &nbsp
          = link_to expence, :method => :delete,
                              :data => { :confirm => 'Точно?.. Уверен?..' } do
            %span.fa.fa-close{"aria-hidden" => "true", 'data-toggle' => 'tooltip', placement: 'left', title: 'Удалить'}

%br
%h4 Платежи (детально)
%table.table.table-sm.table-hover
  %thead
    %tr
      %th.text-center Дата
      %th.text-center Адрес клиента
      %th.text-center ФИО клиента
      %th.text-center Новый?
      %th.text-center Пополнение
      %th.text-center Материалы
      %th.text-center Всего

  %tbody
    - payments.each do |payment|
      %tr
        %td.text-center= payment.created_at.strftime('%d.%m.%Y')
        %td.text-left= payment.client_address
        %td.text-left= payment.client_name
        %td.text-center
          - if payment.client_new_connection?
            %span.fa.fa-check
        %td.text-center= payment.client_payment
        %td.text-center= payment.used_material
        %td.text-center= payment.payment_total
        %td
          = link_to payment do
            %span.fa.fa-info{'aria-hidden' => 'true', 'data-toggle' => 'tooltip', placement: 'left', title: 'Детальная инфомация'} &nbsp
          = link_to payment, :method => :delete,
                             :data => { :confirm => 'Точно?.. Уверен?..' } do
            %span.fa.fa-close{'aria-hidden' => 'true', 'data-toggle' => 'tooltip', placement: 'left', title: 'Удалить'}

app/views/reports/_report_total.html.haml
%blockquote.blockquote
  .text-justify
    %span{style: "padding: 0px 10px;"} &nbsp
    Сумма в кассе (за вычетом процента оператора и дополнительных расходов) - 
    %strong
      #{payments.total_and_percent_report(payments)[1] - payments.total_and_percent_report(payments)[2] - expences.total_expence_report(expences)}
    грн.
    %footer.blockquote-footer.blockquote-reverse
      Клиентов за период -
      %strong
        #{payments.total_and_percent_report(payments)[0]}
    %footer.blockquote-footer.blockquote-reverse
      Всего платежей на сумму -
      %strong
        #{payments.total_and_percent_report(payments)[1]} 
      грн.
    %footer.blockquote-footer.blockquote-reverse
      Всего новых подключений -
      %strong
        #{payments.total_new_connection_report(payments)[0]} 
    %footer.blockquote-footer.blockquote-reverse
      Всего новых подключений на сумму -
      %strong
        #{payments.total_new_connection_report(payments)[1]} 
      грн.
    %footer.blockquote-footer.blockquote-reverse
      Процент оператора
      %strong
        #{payments.total_and_percent_report(payments)[2]} 
      грн.
    %footer.blockquote-footer.blockquote-reverse
      Дополнительные раходы -
      %strong
        #{expences.total_expence_report(expences)}
      грн.

app/views/reports/index.html.haml
= provide(:title, 'Отчеты')

%br
%h4 Отчеты

/ Вкладки
%ul.nav.nav-tabs{:role => "tablist"}
  %li.nav-item
    %a.nav-link.active{"data-toggle" => "tab", :href => "#report_today", :role => "tab"} #{Date.today.strftime('%d.%m.%Y')}
  %li.nav-item
    %a.nav-link{"data-toggle" => "tab", :href => "#report_week", :role => "tab"} за неделю
  %li.nav-item
    %a.nav-link{"data-toggle" => "tab", :href => "#report_month", :role => "tab"} за месяц
  %li.nav-item
    %a.nav-link{"data-toggle" => "tab", :href => "#report_by_date", :role => "tab"} по датам

/ Содержание вкладок
.tab-content
  #report_today.tab-pane.active{:role => "tabpanel"}
    %br
    = render partial: ('reports/report_total'), locals: {payments: @payments_today, expences: @expences_today}
    %br
    = render partial: ('reports/report_detail'), locals: {payments: @payments_today, expences: @expences_today}
  #report_week.tab-pane{:role => "tabpanel"}
    %br
    = render partial: ('reports/report_total'), locals: {payments: @payments_week, expences: @expences_week}
    %br
    = render partial: ('reports/report_detail'), locals: {payments: @payments_week, expences: @expences_week}
  #report_month.tab-pane{:role => "tabpanel"}
    %br
    = render partial: ('reports/report_total'), locals: {payments: @payments_month, expences: @expences_month}
    %br
    = render partial: ('reports/report_detail'), locals: {payments: @payments_month, expences: @expences_month}
  #report_by_date.tab-pane{:role => "tabpanel"}
    %br
    = render template: ('reports/report_by_date')

app/views/reports/pdf_report.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title
      WildPark оператор

%body
  .pdf_content
    

  

%br
%br
%br
%br

!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title
      WildPark оператор

%body
  .pdf_content
    = yield(:report_by_date)

app/views/reports/report_by_date.html.haml
.container-fluid
  = form_tag report_by_date_path, method: 'get', remote: true do
    .form-group
      .row
        .col
          = text_field_tag :start_date,
                           params[:start_date],
                           type: 'date',
                           value: Date.today.to_date,
                           max: Date.today.to_date,
                           class: 'form-control'
        .col
          = text_field_tag :end_date,
                           params[:end_date],
                           type: 'date',
                           value: Date.today.to_date,
                           max: Date.today.to_date,
                           class: 'form-control'
        .col-2
          = submit_tag 'Найти', class: "btn btn"

.report_by_date_total
.report_by_date_detail

app/views/reports/report_by_date.js.erb
$('.report_by_date_total').empty().append('<%= escape_javascript (render partial: 'reports/report_total', locals: {payments: @payments_by_date, expences: @expences_by_date}).html_safe %>');
$('.report_by_date_detail').empty().append('<%= escape_javascript (render partial: 'reports/report_detail', locals: {payments: @payments_by_date, expences: @expences_by_date}).html_safe %>');