config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root 'dashboard#index'

  devise_scope :user do
    get "/sign_up" => "devise/registrations#new", as: :new_user_registration
    get '/sign_in', to: 'devise/sessions#new', as: :new_user_session
    post '/sign_in', to: 'devise/sessions#create', as: :user_session
    delete '/sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users, controllers: {:registrations => :registrations}, skip: [:sessions]
  resources :users, :only => ['index', 'show']

  resources :payments
  resources :materials
  resources :expences
  resources :articles
  
  
  get 'reports', to: 'reports#index'
  get 'report_by_date', to: 'reports#report_by_date'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
%footer
  %p &copy; Company 2016

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_side_nav.html.haml
%ul.nav.flex-sm-column#side_navigation
  - if user_signed_in?
    %li.nav-item
      .nav-link
        = link_to payments_path, class: 'btn btn-sm' do
          %span.fa.fa-money
          &nbsp
          +
          &nbsp
          Платежи
    %li.nav-item
      .nav-link
        = link_to expences_path, class: 'btn btn-sm' do
          %span.fa.fa-money
          &nbsp
          &#8211
          &nbsp
          Расходы
    %li.nav-item
      .nav-link
        = link_to materials_path, class: 'btn btn-sm' do
          %span.fa.fa-cogs
          &nbsp
          Материалы
    %li.nav-item
      .nav-link
        = link_to reports_path, class: 'btn btn-sm' do
          %span.fa.fa-calendar
          &nbsp
          Отчеты
    %li.nav-item
      .nav-link
        =link_to articles_path, class: 'btn btn-sm' do
          %span.fa.fa-newspaper-o
          &nbsp
          Статьи

app/views/layouts/_top_nav.html.haml
%nav.navbar.navbar-toggleable-sm.navbar-light.bg-faded
  %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarToggler",
                                                "aria-expanded" => "false",
                                                "aria-label" => "Toggle navigation",
                                                "data-target" => "#navbarToggler",
                                                "data-toggle" => "collapse",
                                                :type => "button"}
    %span.navbar-toggler-icon
  %a.navbar-brand{:href => "/"}
    WildPark
    %sub
      оператор
  #navbarToggler.collapse.navbar-collapse
    %ul.nav.navbar-nav.mr-auto
    %ul.nav.navbar-nav.pull-sm-right.mt-2.mt-md-0
      - if user_signed_in?
        - if can? :manage, :rails_admin
          %li.nav-item
            .nav-link
              = link_to rails_admin_path, class: 'btn btn-sm', data: {toggle: 'tooltip', placement: 'left'}, title: 'Перейти в админку' do
                %span.fa.fa-gear
        %li.nav-item
          .nav-link
            = link_to current_user.email, user_path(current_user), class: 'btn btn-sm'
        %li.nav-item
          .nav-link
            = link_to 'Выход', destroy_user_session_path, :method => 'delete', class: 'btn btn-sm'
      - else
        %li.nav-item
          .nav-link
            = link_to 'Вход', new_user_session_path, class: 'btn btn-sm'
        %li.nav-item
          .nav-link
            = link_to 'Регистрация', new_user_registration_path, class: 'btn btn-sm'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= full_title(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    /= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    /= javascript_include_tag  "//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"
      = javascript_include_tag "jquery", "application"


    %link{:href => "http://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/


  %body
    // Верхняя навигация
    = render ('layouts/top_nav')
    %br
    - if user_signed_in?
      .row
        .col-sm-3.togglier
          .container
            // Боковая навигация
            = render ('layouts/side_nav')
        .col-sm-9
          .container-fluid
            = render ('layouts/messages')
            = yield
      //.row.container-fluid
      //  = render ('layouts/footer')
    - else
      .container
        .row.justify-content-center
          .col-6
            = render ('layouts/messages')
      = yield